openapi: "3.0.0"
info:
  version: 0.0.3
  title: RateMon API
  description: API exposing CMS trigger rates exported by the RateMon tools
servers:
  - url: http://ater.cern.ch/api/v1

paths:

  /runRatesROOT:
    get:
      tags: [Trigger Rates]
      description: |
        Get ROOT plot of the rates of the specified trigger for a given CMS run number
      operationId: app.getRatesROOT
      parameters:
        - name: runNumber
          in: query
          description: "Run number"
          example: 370772
          required: true
          style: form
          schema:
            type: integer
        - name: triggerKey
          in: query
          description: "Trigger name key. Must be part of the [monitorlist_COLLISIONS](https://gitlab.cern.ch/cms-tsg-fog/ratemon/-/blob/api/ratemon/TriggerLists/monitorlist_COLLISIONS.list) list."
          example: HLT_IsoMu24
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ROOT binary file of the computed plot
        '400':
          description: Bad Request

  /ratesJSON:
    get:
      tags: [Trigger Rates]
      description: |
        Get a JSON file with raw rates of the specified trigger for a given CMS run or LHC fill number
      operationId: app.getRatesJSON
      parameters:
        - name: runOrFillNumber
          in: query
          description: "Run or fill number"
          example: 9072
          required: true
          style: form
          schema:
            type: integer
        - name: triggerKey
          in: query
          description: "Trigger name key"
          example: HLT_IsoMu24
          required: true
          schema:
            type: string
        - name: queryByFill
          in: query
          description: "Flag for querying by fill"
          example: true
          required: true
          schema:
            type: boolean
        - name: createFit
          in: query
          description: "Flag to create a fit to the data. [If false, the reference fit from [ratemon/ratemon/Fits](https://gitlab.cern.ch/cms-tsg-fog/ratemon/-/tree/master/ratemon/Fits) is used.]"
          example: true
          required: true
          schema:
            type: boolean
      responses:
        '200':
          description: JSON file with the raw trigger rates
        '400':
          description: Bad Request
