dsn_info:
  'online': 'cms_omds_lb'
  'offline': 'cms_omds_adg'

hlt_connect:
  'user': 'cms_hlt_r'
  'passwd': '__cms_hlt_r_pass__'


trg_connect:
  'user': 'cms_trg_r'
  'passwd': '__cms_trg_r_pass__'
