katharsis:
  searchPackage: ch.cern.cms.daq.oms.api.aggregation.model

server:
  type: simple
  applicationContextPath: /api/v1
  adminContextPath: /admin
  connector:
    type: http
    port: 80

logging:
  level: INFO

  appenders:
    - type: console
    
aggregation:
  db_Hostname: cmsonr1-s.cern.ch
  db_Port:     10121
  db_Service:  cms_omds_lb.cern.ch
  db_User:     CMS_WBM_R
  db_Password: PASSWORD
  db_MinPoolSize: 8
  db_MaxPoolSize: 32
  maxPageLimit: 100000
  defaultPageLimit: 100
 
assets:
  overrides:
    /endpoints: src/main/resources
